package net.legacy.platform.core.enums;

public enum NotificationChannel {

    DIRECT_MESSAGE(0),
    ENCRYPTED_WHISPER(1),
    TEAM_ROOM(2),
    DEPARTMENT_CHANNEL(3),
    ORGANIZATION_HUB(4),
    ENTERPRISE_ALLIANCE(5),
    SYSTEM_METRIC_DESCRIPTION(6),
    OPERATIONAL_TIP(7),
    STANDARD_NOTICE(8),
    ALERT_NOTICE_LV_2(9),
    ADMIN_COMMAND_CHAT(10),
    CRITICAL_SYSTEM_NOTICE(11),
    BROADCAST_CLUSTER(12),
    BROADCAST_GLOBAL(13),
    BROADCAST_HIGH_PRIORITY(14),
    ASSET_ALERT_NOTIFIER(15),
    ASSET_METADATA_STREAM(16),
    THEME_PURPLE(17),
    THEME_YELLOW_WHITE(18),
    NETWORK_BRIDGE_NOTIFY(19),
    PREVIEW_STREAM_NOTIFY(20),
    AUTOMATED_PROCESS_MSG(21),
    TASK_EXPEDITION_HUB(22),
    ASSET_LOG_MESSAGE(23),
    EVENT_METRIC_WINDOW(24),
    LOGGER_ASSET_ALERT(25),
    LOGGER_GLOBAL_STREAM(26),
    VISUAL_BANNER_NOTIFY(27),
    TELEMETRY_PICKUP_STREAM(28),
    CLUSTER_IDENTITY_TAG(29),
    CORE_METRIC_LOG(30),
    COMPLAINT_CLAIM_TICKET(31),
    EXTERNAL_WEBHOOK_STREAM(32),

    INTEGRATION_REWARD_LOG(33),
    TELEMETRY_RED_ALERT(34),
    TELEMETRY_RED_ALERT_ALTER(35),
    ASSET_METADATA_STREAM_ALTER(36),
    SYSTEM_TEXT_LEGACY_1(37),
    SYSTEM_TEXT_LEGACY_2(38),
    METRIC_WIDGET_CONTAINER_1(39),
    METRIC_WIDGET_CONTAINER_2(40),
    SYSTEM_TEXT_LEGACY_3(41);

    private final int channelCode;

    private NotificationChannel(final int channelCode) {
        this.channelCode = channelCode;
    }

    public int getChannelCode() {
        return this.channelCode;
    }

}
